syntax = "proto3";

enum Form {
    Gas = 0;
    Liquid = 1;
    Solid = 2;
}

message Fraction {
    uint32 n = 1;    // Numerator
    uint32 d = 2;    // Denominator
}

message CraftingObject {
    string name = 1;
    repeated uint32 recipes = 2;
    Form form = 3;
}

message Recipe {
    string name = 1; 
    map<uint32, Fraction> ingredients = 2;  // Maps between ingredient ID and amount
    map<uint32, Fraction> products = 3;     // Maps between product ID and amount
    Fraction duration = 4;                  // Duration (in seconds) to make all listed products
    bool is_alternate = 5;
    uint32 produced_in = 6;                 // Building ID
}

message Building {
    string name = 1;
    bool generates_power = 2;                    // True if the machine generates power, false if it consumes power
    Fraction power_consumption = 3;             // Base power consumption (MW)
    Fraction speed_power_exponent = 4;          // Power consumption exponent of under/overclocking
    Fraction production_power_exponent = 5;     // Power consumption exponent of overslooping
    uint32 num_sloop_slots = 6;                 // Max number of sloops that can be installed in the machine
}

message GameData {
    repeated CraftingObject crafting_objects = 1;
    repeated Recipe recipes = 2;
    repeated Building buildings = 3;
    repeated uint32 crafting_ingredients = 5;   // IDs of items used as ingredients in recipes
    repeated uint32 crafting_products = 6;      // IDs of items that can be produced using recipes
    repeated uint32 trivial_ingredients = 7;    // IDs of ingredients that are trivial by default
}

message WebsiteState {
    uint32 product_id = 1;
    Fraction display_multiplier = 2;
    bool show_byproducts = 3;
    map<uint32, uint32> alternate_recipes = 4;  // Maps between an object ID and the ID of the recipe that's currently selected for it.
    repeated uint32 trivial_resources = 5;

    // Field beyond this point must be optional in order to stay compatible
    // with older versions of the website
}
