// Docs:
// https://devhints.io/jsdoc
// https://tom-select.js.org/docs/
// https://mermaid.js.org/config/setup/mermaid/interfaces/MermaidConfig.html
// https://mathjs.org/docs/datatypes/fractions.html
// https://protobuf.dev/programming-guides/proto3/
// https://github.com/protobufjs/protobuf.js/
import game_data from "@/GameData/GameData.mjs";
import {assert, any, reduce, map, fractionMax, formatFrac} from "@/Utils.mjs";
import {Graph, Node, Edge} from "@/Graph.mjs";
import {g_, SCNode} from "@/Common.mjs";
import generateGraphData from "@/GraphGeneration.mjs";
import Config from "@/Config.mjs";

/** @import { GameObjectId, Recipe, CraftingObject } from "@/GameData/GameData.mjs" */
/** @import { MyEdgeInfo } from "@/Common.mjs" */

import mermaid from "mermaid";
import * as mathjs from 'mathjs';
import {fraction, Fraction} from 'mathjs';

/* TODOs:
- Add getters and setters to everything in "Config" to remove the need to call "notifyChange".
- "generateGraphPhase1" assumes that the SVG elements are generated in the same order that they are specified in the
   mermaid input. Check this assumption!
- Don't display fractions when they're 1/1.
- Minify the autogenerated JSON to contain as little information as possible (i.g. dicts -> lists with keys
  as indices). Then, website initialization will process the data into a format more convenient to the
  developer (much like the current format, maybe even better). Also use the minified format for the URL parameters.
- On each node in the graph, show the name (and icon?) of the machine that's required to produce it. Exclude trivial
  and byproduct nodes.
- when a recipe is selected, show the following info in the sidebar:
    - Number of requires machined of each type (maybe even icons?)
    - Amount of power required.
        - If the current recipe includes power generation (for example, plutonium fuel rod recipe
          includes uranium waste, which is produced by generating power), subtract this amount from the total required power
          to show net value (will most likely be negative in this scenario). In this case, maybe display 2 separate values:
          one for power required, and another for power generated.
        - If number of machines isn't whole, either round up or calculate power usage when underclocked.
*/


/**
 * Returns the number of "lines" that should be reserved for a node overlay
 * @param {SCNode} node 
 * @returns {number}
 */
function estimateNodeOverlayHeight(node) {
    // Object name + icon + production
    let result = 3;

    if (!node.isPureByproduct()) {
        const num_recipes = node.recipes().length;
        if (!node.isTrivial()) {
            // Recipe selection
            if (num_recipes > 1)
                ++result;

            // Machines required
            ++result;
        }

        // "Trivial?" checkbox
        if (num_recipes > 0)
            ++result;
    }

    return result;
}

/**
 * @param {Graph<SCNode, MyEdgeInfo>} graph 
 * @param {number} stroke_width - stoke width in pixels
 * @returns {[string, Node<SCNode, MyEdgeInfo>[], Edge<SCNode, MyEdgeInfo>[]]}
 */
function toMermaid(graph, stroke_width) {
    let ordered_nodes = [...graph.nodes()];
    let ordered_edges = [...graph.links()];

    let result = "flowchart-elk TD\n";

    for (const node of ordered_nodes) {
        const overlay_height = estimateNodeOverlayHeight(node.data);

        // Sub 1 because we already have 1 line
        result += `${node.data.obj().id}["$AAAAAAAAAAAAAAAAAA${'<br/>'.repeat(overlay_height - 1)}"]\n`;
    }

    result += '\n';

    for (const edge of ordered_edges) {
        result += `${edge.source.data.obj().id}--AAAAAAAAA</br>AAAAAAAAA-->${edge.target.data.obj().id}\n`;
    }

    result += `linkStyle default stroke-width:${stroke_width}px;`;

    return [result, ordered_nodes, ordered_edges];
}

const FRACTION_CHARACTERS_FILTER_REGEX = /[^\d.\/()]/g;

/**
 * @param {HTMLLabelElement} editable_multiplier_label 
 */
function initEditableMultiplierLabel(editable_multiplier_label) {
    editable_multiplier_label.contentEditable = "plaintext-only";

    let current_val = null;

    /** @param {InputEvent} e */
    editable_multiplier_label.oninput = function(e) {
        // Filter out characters that can't be used to represent a fraction
        // Note: Each time the "textContent" is set, the text cursor is reset to the beginning, even if
        //       the same value is written. To prevent that, we set it only if it was changed, i.e., only
        //       if an invalid character was entered. 
        const new_content = e.target.textContent.replace(FRACTION_CHARACTERS_FILTER_REGEX, "");
        if (new_content != e.target.textContent)
            e.target.textContent = new_content;
    }

    /** @param {KeyboardEvent} e */
    editable_multiplier_label.onkeydown = function(e) {
        // Put the label out of focus when pressing escape or enter
        if (("Enter" == e.key) || ("Escape" == e.key)) {

            // When enter is pressed, calculate the display multiplier that's required for setting the current label
            // to the value that was entered. Then, apply this display multiplier to the entire graph.
            if ("Enter" == e.key) {
                let new_value = null;

                // Parsing user input as a fraction, expect parsing errors.
                try { new_value = fraction(e.target.textContent); } catch (err) {}

                // Will be null if the user has entered an invalid fraction
                if (null !== new_value) {
                    const prev_value = fraction(current_val);
                    const mult_mult = mathjs.divide(new_value, prev_value);

                    const new_display_mult = mathjs.multiply(g_.config.display_multiplier, mult_mult);

                    // Disallow the value 0, since it will break the next calculation, because it will attempt
                    // to divide the new value by zero.
                    if (!mathjs.isZero(new_display_mult)) {
                        // Need to update this after the next blur (which will happen now), because our "blur" handler
                        // resets the value that's currently being edited.
                        e.target.addEventListener(
                            "blur",
                            (e) => { updateDisplayMultiplier(new_display_mult); },
                            {once: true}
                        );
                    }
                }
            }

            e.preventDefault();
            e.target.blur();
        }
    }

    /** @param {FocusEvent} e */
    editable_multiplier_label.onfocus = function(e) { current_val = e.target.textContent; }

    editable_multiplier_label.addEventListener(
        "blur",
        /** @param {FocusEvent} e */
        (e) => {
            window.getSelection().removeAllRanges();

            // Restore the content to what it was, because any change should be reflected in the global
            // display multiplier, and not here.
            e.target.textContent = current_val;
        }
    );
}

/**
 * @param {SVGGElement} node_svg_element 
 * @param {Node<SCNode, MyEdgeInfo>} node
 */
function createNodeOverlay(node_svg_element, node) {
    // Clone the template
    const clone = g_.html_elements.nodeOverlayTemplate.content.cloneNode(true);
    assert(1 == clone.childElementCount);

    /** @type {HTMLDivElement} */
    const overlay = clone.firstChild;
    node.data.html = overlay;

    const obj = node.data.obj();

    const is_pure_byproduct = node.data.isPureByproduct();

    // Pure byproducts take precedence over trivial resources
    const is_trivial = is_pure_byproduct ? false : node.data.isTrivial();

    if (is_trivial || is_pure_byproduct) {
        overlay.style.backgroundColor = is_trivial ? 'lightblue' : 'lightgreen';
        overlay.querySelector(".machines-required-container").remove();
    }
    else if (g_.product_node == node) {
        overlay.style.backgroundColor = 'pink';
    }

    // Initialize labels
    overlay.querySelector('.node-item-name').textContent = obj.name;

    // Initialize image
    overlay.querySelector('.node-icon').src = `images/game_icons/${obj.id}.png`;

    //
    // Initialize trivial checkbox
    //
    if ((0 == obj.recipes.length) || is_pure_byproduct) {
        // An object with no recipes is forced to be trivial (remove the option to change it)
        assert(is_trivial || is_pure_byproduct);
        overlay.querySelector(".is-trivial-container").remove();
    } else {
        /** @type {HTMLInputElement} */
        const trivial_checkbox = overlay.querySelector(".is-trivial-checkbox");
        trivial_checkbox.checked = is_trivial;
        trivial_checkbox.onclick = function(e) {
            if (e.target.checked)
                g_.config.trivial_resources.add(obj.id);
            else
                g_.config.trivial_resources.delete(obj.id);

            g_.config.notifyChange();
            generateGraph();
        }
    }

    //
    // Initialize alternate recipes select, or remove if there are none
    //
    if (is_trivial || is_pure_byproduct || (obj.recipes.length <= 1)) {
        overlay.querySelector(".node-alternate-recipes").remove();
    } else {
        let recipe_index = g_.config.alternate_recipes.get(obj.id);
        if (undefined === recipe_index)
            recipe_index = 0;

        /** @type {HTMLSelectElement} */
        const alternate_recipes_select = overlay.querySelector(".node-alternate-recipes > select");
        for (const recipe of obj.recipes) {
            alternate_recipes_select.add(new Option(recipe.name));
        }

        alternate_recipes_select.selectedIndex = node.data.obj().recipes.indexOf(node.data.selectedRecipe());

        alternate_recipes_select.oninput = function(e) {
            g_.config.alternate_recipes.set(obj.id, obj.recipes[e.target.selectedIndex]);
            g_.config.notifyChange();
            generateGraph();
        };
    }

    // Inject a "foreignObject" element into the node
    const foreign_obj = document.createElementNS("http://www.w3.org/2000/svg", "foreignObject");
    foreign_obj.appendChild(overlay);

    // Position the "foreignObject" over the node
    const rect = node_svg_element.getBBox({fill: true, stroke: true, markers: true, clipped: false});
    foreign_obj.setAttribute("x", rect.x-2);
    foreign_obj.setAttribute("y", rect.y-2);
    foreign_obj.setAttribute("width", rect.width+4);
    foreign_obj.setAttribute("height", rect.height+4);

    node_svg_element.appendChild(foreign_obj);
}

/**
 * @param {SVGForeignObjectElement} edge_label_element 
 * @param {SVGPathElement} edge_path_element 
 * @param {Edge<SCNode, MyEdgeInfo>} edge
 */
function createEdgeOverlay(edge_label_element, edge_path_element, edge) {
    edge.data.path_element = edge_path_element;
    if (edge.data.is_byproduct) {
        edge_path_element.style.stroke = 'orange';
    }

    // Clone the template
    const clone = g_.html_elements.edgeOverlayTemplate.content.cloneNode(true);
    assert(1 == clone.childElementCount);

    /** @type {HTMLDivElement} */
    const overlay = clone.firstChild;
    edge.data.html = overlay;

    overlay.querySelector('.edge-ratio-label').textContent = formatFrac(edge.data.total_fraction);

    edge_label_element.replaceChildren(overlay);
}

/**
 * Generates the UI for the given graph
 * @param {Node<SCNode, MyEdgeInfo>} product_node
 * @param {boolean} recalc_mult - Whether the display multiplier should be recalculated
 */
async function generateGraphUI(product_node, recalc_mult) {
    const [graph_mermaid, ordered_nodes, ordered_edges] = toMermaid(product_node.graph, 2);
    const render_result = await mermaid.render('graphSvg', graph_mermaid);

    g_.html_elements.graphContainer.innerHTML = render_result.svg;

    /** @type {SVGElement} */
    const graph_svg = g_.html_elements.graphContainer.querySelector('#graphSvg');

    /** @type {NodeListOf<SVGGElement>} */
    const node_svg_elements = graph_svg.querySelectorAll('.nodes > g.node.default');

    /** @type {NodeListOf<SVGPathElement>} */
    const edge_path_svg_elements = graph_svg.querySelectorAll('.edges.edgePaths > path');

    /** @type {NodeListOf<SVGForeignObjectElement>} */
    const edge_label_svg_elements = graph_svg.querySelectorAll('.edgeLabels > g > g > foreignObject');

    assert(node_svg_elements.length == ordered_nodes.length);
    assert(edge_path_svg_elements.length == ordered_edges.length);
    assert(edge_label_svg_elements.length == ordered_edges.length);

    // Create overlays for the nodes and associate them with the relevant node objects
    for (let i = 0; i < ordered_nodes.length; ++i) {
        createNodeOverlay(node_svg_elements[i], ordered_nodes[i])
    }

    // Create edge overlays and associate them with the relevant edge objects.
    // Also associate the edge path.
    for (let i = 0; i < ordered_edges.length; ++i) {
        createEdgeOverlay(edge_label_svg_elements[i], edge_path_svg_elements[i], ordered_edges[i]);
    }

    for (const editable_multiplier_label of graph_svg.querySelectorAll(".editable-multiplier-label")) {
        initEditableMultiplierLabel(editable_multiplier_label);
    }

    // Reset the pan and zoom
    g_.panzoom.reset({ animate: false });

    if (recalc_mult)
        updateDisplayMultiplierAuto();
    else
        updateOverlay();
}

/**
 * Regenerates the entire graph. Should only be called if the structure of the graph was changed.
 * @param {boolean} recalc_mult - Whether the display multiplier should be recalculated
 */
export async function generateGraph(recalc_mult=false) {
    g_.product_node = generateGraphData(g_.config.selected_product);

    generateGraphUI(g_.product_node, recalc_mult);
}

/**
 * @param {Fraction} frac 
 * @returns {Fraction}
 */
function applyDisplayMultiplier(frac) {
    return mathjs.multiply(frac, g_.config.display_multiplier);
}

/** Updates the overlay according to the display multiplier */
function updateOverlay() {
    const graph = g_.product_node.graph;
    for (const node of graph.nodes()) {
        node.data.html.querySelector('.production-rate-label').textContent = formatFrac(applyDisplayMultiplier(node.data.productionPerMinute()), false);

        if (!node.data.isTrivial() && !node.data.isPureByproduct()) {
            node.data.html.querySelector('.machines-required-label').textContent = formatFrac(applyDisplayMultiplier(node.data.machinesRequired()), false);
        }
    }

    for (const edge of graph.links()) {
        edge.data.html.querySelector('.edge-production-label').textContent = formatFrac(applyDisplayMultiplier(mathjs.multiply(edge.data.production_required, 60)), false);
    }
}

/**
 * @param {GameObjectId} product_id - the ID of the new product
 * @param {boolean} recalc_mult - Whether the display multiplier should be recalculated
 */
export function updateSelectedProduct(product_id, recalc_mult) {
    g_.config.selected_product = game_data.crafting_objects[product_id];
    g_.config.notifyChange();
    generateGraph(recalc_mult);
}

export function resetAlternateRecipes() {
    // Re-render only if a non-alternate recipe is currently selected
    const should_re_render_graph = any(
        g_.config.alternate_recipes.entries(),
        ([obj_id, selected_recipe]) => 0 != game_data.crafting_objects[obj_id].recipes.indexOf(selected_recipe)
    );

    g_.config.alternate_recipes.clear();
    g_.config.notifyChange();

    if (should_re_render_graph)
        generateGraph();
}

export function resetTrivialResources() {
    const new_trivial_resources = new Set(game_data.trivial_ingredients.map(obj => obj.id));

    const symmetric_diff = new_trivial_resources.symmetricDifference(g_.config.trivial_resources);

    // If nothing was changed, return
    if (0 == symmetric_diff.size)
        return;

    g_.config.trivial_resources = new_trivial_resources;
    g_.config.notifyChange();

    // If the difference contains at-least one node in the current graph, re-generate the entire graph
    if ((null != g_.product_node) && any(g_.product_node.graph.nodes(), (node) => symmetric_diff.has(node.data.obj().id)))
        generateGraph()
}

/**
 * @param {Fraction=} new_value 
 */
export function updateDisplayMultiplier(new_value) {
    if (undefined === new_value) {
        new_value = fraction(g_.html_elements.displayMultiplierInput.value);
    } else {
        g_.html_elements.displayMultiplierInput.value = formatFrac(new_value, true, true);
    }

    g_.config.display_multiplier = fraction(new_value);
    g_.config.notifyChange();
    updateOverlay();
}

export function updateDisplayMultiplierAuto() {
    // Calculate the LCM of the denominators of all machines required.
    // This will yield a multiplier that, when applied, makes the "machines required" of all nodes
    // into a whole number.
    let computed_lcm = fraction(1);
    for (const node of g_.product_node.graph.nodes()) {
        if (!node.data.isTrivial() && !node.data.isPureByproduct())
            computed_lcm = mathjs.lcm(computed_lcm, node.data.machinesRequired().d);
    }

    updateDisplayMultiplier(computed_lcm);
}

/** @param {PointerEvent} e */
export function toggleShowByproducts(e) {
    g_.config.show_byproducts = e.target.checked;
    g_.config.notifyChange();

    // Re-generate the graph, unless box was unchecked AND current graph didn't have byproducts.
    if (e.target.checked || any(g_.product_node.graph.links(), (edge) => edge.data.is_byproduct))
        generateGraph();
}

/** 
 * Generate graph data for all possible combinations of:
 * - Target products
 * - Selected trivial resources
 * - Selected alternate recipes
 * 
 * Currently very slow and pretty much unusable.
 * TODOs:
 * - Optimize by not checking combinations that don't add new information. For example, don't bother generating
 *   the graph data for smart plating with a different alternate recipe for uranium fuel rod, because the two
 *   are unrelated.
 * - Maybe, instead of going over all possible combinations, also add a variation which chooses a random combination
 *   each time. Not sure if it's better though.
 */
function _testAll() {
    const prev_config = g_.config;
    g_.config = new Config();
    g_.config.display_multiplier = fraction(1);
    g_.config.show_byproducts = true;

    // Subtract the default trivial ingredients, because we always keep those as trivial
    const crafting_obj_ids = [...new Set(game_data.crafting_objects.map(obj => obj.id)).difference(new Set(game_data.trivial_ingredients.map(obj => obj.id)))];

    const num_trivial_items_combinations = Math.pow(2, crafting_obj_ids.size);
    const num_recipe_combinations = reduce(
        game_data.crafting_products,
        (product, obj) => product * obj.recipes.length,
        1
    );

    // Iterate through all craftable objects
    for (const crafting_product of game_data.crafting_products) {
        console.time(crafting_product.name);

        // Iterate through all possible combinations of trivial resources (excluding items that are trivial by default, these
        // will always be selected as trivial for this test)
        for (let i = 0; i < num_trivial_items_combinations; ++i) {
            const str = i.toString(2).padStart(crafting_obj_ids.size, '0');
            g_.config.trivial_resources = new Set(game_data.trivial_ingredients.map(obj => obj.id));
            for (let j = 0; j < str.length; ++j) {
                if ('1' == str[j])
                     g_.config.trivial_resources.add(crafting_obj_ids[j]);
            }
            
            // Iterate through all possible combinations of selected recipes
            g_.config.alternate_recipes = new Map(game_data.crafting_products.map(obj => [obj.id, 0]));
            for (let j = 0; j < num_recipe_combinations; ++j) {
                for (const crafting_prod of game_data.crafting_products) {
                    const num_recipes = crafting_prod.recipes.length;
                    const new_recipe_index = (g_.config.alternate_recipes.get(crafting_prod.id) + 1) % num_recipes;
                    g_.config.alternate_recipes.set(crafting_prod.id, new_recipe_index);

                    // If we overflowed, carry to the next recipe.
                    // Otherwise, stop.
                    if (new_recipe_index > 0)
                        break;
                }

                try
                {
                    const data = generateGraphData(crafting_product);
                } catch {
                    g_.config.notifyChange();
                    alert("A test has failed, copy the current URL to reproduce");

                    // Restore previous config
                    g_.config = prev_config; 
                    g_.config.notifyChange();
                    return;
                }
            }
            
        }

        console.timeEnd(crafting_product.name);
    }
    
    // Restore previous config
    g_.config = prev_config;
}

// Must be last
import initApp from "@/Init.mjs";
initApp();

//_testAll();
