import re
import json
import shutil
from os import path
from types import NoneType
from functools import reduce
from fractions import Fraction
from typing import NamedTuple, Any, TypeAlias, Iterable


# Corresponds to the "ClassName" element in the JSON file.
# For example: "Desc_SpaceElevatorPart_1_C".
GameObjectId: TypeAlias = str

# Corresponds to the "NativeClass" element in the JSON.
# For example: "FGItemDescriptor".
GameObjectCategoryName: TypeAlias = str

# Corresponds to an entry inside the "Classes" member of each top-level entry in the JSON.
# For example:
# {
#   "ClassName": "Desc_AluminumIngot_C",
#   "mDisplayName": "Aluminum Ingot",
#   ...
# }
GameObject: TypeAlias = dict[str, Any]

CountedItems: TypeAlias = dict[GameObjectId, Fraction]


class Recipe(NamedTuple):
    name: str
    products: CountedItems
    ingredients: CountedItems
    duration: Fraction
    is_alternate: bool
    produced_in: set[str]


class CraftingObject(NamedTuple):
    id: str
    name: str
    recipes: list[GameObjectId]
    form: str


def jsonify(obj):
    """Prepares the given object for serialization using JSON"""
    if isinstance(obj, Fraction):
        return {'n': obj.numerator, 'd': obj.denominator}

    if isinstance(obj, (int, float, str, bool, NoneType)):
        return obj

    if isinstance(obj, dict):
        return {
            k: jsonify(v)
            for k, v
            in obj.items()
        }

    if isinstance(obj, (list, tuple, set)):
        if isinstance(obj, tuple) and hasattr(obj, '_fields'):
            return jsonify(obj._asdict())
        else:
            return [jsonify(item) for item in obj]

    raise TypeError(f'Unknown type: {type(obj)}')


class SatisfactoryParser:
    _COMMON_OBJECT_CATEGORY_NAME_PREFIX = r"/Script/CoreUObject.Class'/Script/FactoryGame."
    _CRAFTING_OBJ_LIST_REGEX = re.compile(r"""\(ItemClass=\".+?\.([^']+)'\",Amount=(\d+)\)""")
    _OBJECT_NAME_REGEX = re.compile(r"^([a-zA-Z\d]+)_(.+)_C$")
    _CAMEL_CASE_REGEX = re.compile(r"([a-z])([A-Z])")
    _ICON_STRING_REGEX = re.compile(r"Texture2D /Game/(.*(\w+))\.\2")
    _PRODUCED_IN_REGEX = re.compile(r'\"[^,]+\.(\w+)\"')
    _ALTERNATE_RECIPE_NAME_PREFIX = "Alternate: "

    def __init__(self, doc_file_path=r"C:\Program Files (x86)\Steam\steamapps\common\Satisfactory\CommunityResources\Docs\en-US.json"):
        self._all_objects, self._categorized_objects = self._preprocess_doc_file(doc_file_path)
        self._recipes = self._process_recipes()

        self._crafting_ingredients = set()
        self._crafting_products = set()
        for recipe in self._recipes.values():
            self._crafting_ingredients |= set(recipe.ingredients.keys())
            self._crafting_products |= set(recipe.products.keys())

        self._crafting_objects = self._process_crafting_objects()
        self._trivial_ingredients = self._calculate_trivial_ingredients()

    def generate_data_file_content(self):
        def sort_by_display_name(object_ids: Iterable[GameObjectId]) -> list[GameObjectId]:
            return list(sorted(object_ids, key=lambda name: self._crafting_objects[name].name))

        data = jsonify({
            'crafting_objects': self._crafting_objects,
            'crafting_products': sort_by_display_name(self._crafting_products),
            'crafting_ingredients': sort_by_display_name(self._crafting_ingredients),
            'trivial_ingredients': sort_by_display_name(self._trivial_ingredients),
            'recipes': self._recipes,
        })

        # Remove fields that aren't currently used by teh website
        # TODO: if you need it for the website, make sure to sort this field so that
        # the autogenerated file won't change each time even though there aren't any
        # real changes.
        for recipe in data['recipes'].values():
            del recipe["produced_in"]

        return \
            f"""/* This file is auto-generated! */

/** @import {{Fraction}} from "mathjs" */

/**
 * @typedef {{string}} GameObjectId
 * @typedef {{Object.<string, Fraction>}} CountedItems
 * @typedef {{{{
 *      name: GameObjectId,
 *      products: CountedItems,
 *      ingredients: CountedItems,
 *      duration: Fraction,
 *      is_alternate: boolean,
 *      produced_in: string[]
 * }}}} Recipe
 *
 * @typedef {{{{
 *      id: string,
 *      name: string,
 *      recipes: GameObjectId[],
 *      form: "SOLID" | "LIQUID" | "GAS"
 * }}}} CraftingObject
 */

/**
 * @type {{{{
 *      crafting_objects: Object.<string, CraftingObject>,
 *      crafting_products: GameObjectId[],
 *      crafting_ingredients: GameObjectId[],
 *      trivial_ingredients: GameObjectId[],
 *      recipes: Object.<string, Recipe>
 *  }}}}
 */
const game_data = {json.dumps(data, sort_keys=True, separators=(',', ':'))};
export default game_data;
"""

    # To extract the icons:
    # - Follow the guide in "https://docs.ficsit.app/satisfactory-modding/latest/Development/ExtractGameFiles.html" up to
    #   (and including) the "Specify Custom Version and Mapping" section.
    # - In the "Archives" tab, open "FactoryGame-windows.utoc"
    # - Ctrl+Shift+F > search for the string "/UI/"
    # - Ctrl+A > Right Click > "Save Texture"
    # - This will save most of the textures, but not all of them.
    # - To find the other missing textures, uncomment the lines in the script which print the "mSmallIcon" member
    #   of each object if it doesn't contain the string "/UI/".
    # - Manually extract these one by one (there should be around 5 files in total).
    # Note: Alternatively, it's possible to extract all the textures in teh game, but it will take a lot of time
    #       and a lot of disk space.
    # - Run this function with "fmodel_output_dir_path" set to FModel's "Output" directory (which is automatically created
    #   next to "FModel.exe"
    def process_extracted_assets(self, fmodel_output_dir_path):
        asserts_base_path = path.join(fmodel_output_dir_path, 'Exports', 'FactoryGame', 'Content')
        target_base_path = path.join(path.dirname(__file__), '..', 'website', 'public', 'images', 'game_icons')
        for crafting_obj_id in self._crafting_objects:
            obj = self._all_objects[crafting_obj_id]

            match = self._ICON_STRING_REGEX.match(obj['mSmallIcon'])
            shutil.copyfile(
                path.join(asserts_base_path, f'{match[1]}.png'),
                path.join(target_base_path, f'{crafting_obj_id}.png')
            )

    @classmethod
    def _preprocess_doc_file(cls, doc_file_path: str) -> tuple[
        dict[GameObjectId, GameObject],
        dict[GameObjectCategoryName, dict[GameObjectId, GameObject]]
    ]:
        with open(doc_file_path, 'rb') as f:
            game_object_categories = json.load(f)

        #
        # Base processing for all objects
        #
        all_objects: dict[GameObjectId, GameObject] = {}
        categorized_objects: dict[GameObjectCategoryName, dict[GameObjectId, GameObject]] = {}
        for game_object_category in game_object_categories:
            assert game_object_category['NativeClass'].startswith(cls._COMMON_OBJECT_CATEGORY_NAME_PREFIX)
            category_name = game_object_category['NativeClass'][len(cls._COMMON_OBJECT_CATEGORY_NAME_PREFIX):].rstrip("'")

            current_category_objects = {}
            for game_object in game_object_category['Classes']:
                game_object['id'] = game_object['ClassName']
                game_object['name'] = cls._get_object_display_name(game_object)
                game_object['native_class'] = category_name

                assert game_object['id'] not in all_objects
                all_objects[game_object['id']] = game_object
                current_category_objects[game_object['id']] = game_object

            categorized_objects[category_name] = current_category_objects

        return all_objects, categorized_objects

    def _process_recipes(self) -> dict[GameObjectId, Recipe]:
        recipes: dict[GameObjectId, Recipe] = {}
        for recipe_id, recipe in self._categorized_objects['FGRecipe'].items():
            produced_in = set(self._PRODUCED_IN_REGEX.findall(recipe['mProducedIn']))

            # Ignore recipes that can't be automated
            if produced_in <= {'BP_BuildGun_C', 'FGBuildGun', 'BP_WorkshopComponent_C'}:
                continue

            products = self._parse_crafting_obj_list(recipe['mProduct'])
            ingredients = self._parse_crafting_obj_list(recipe['mIngredients'])

            duration = Fraction(recipe['mManufactoringDuration'])
            is_alternate = recipe['mDisplayName'].startswith('Alternate: ')
            recipe_name = recipe['name']

            # Force build converted recipes to be alternate, and update the recipe name accordingly
            # Unless the name of the product is the name of the recipe, in which case it's the main recipe.
            # For example: time crystal, dark matter residue and excited photonic mater.
            if ("Build_Converter_C" in produced_in) and \
               (
                    (1 != len(products)) or \
                    (self._all_objects[next(iter(products.keys()))]['name'] != recipe_name)
            ):
                is_alternate = True
                recipe_name = f"Build converter: {recipe_name}"

            # Force "unpackage" recipes to be alternate
            if "Build_Packager_C" in produced_in and "Unpackage" in recipe['id']:
                is_alternate = True

            # Strip common prefix for alternate recipes
            if recipe_name.startswith(self._ALTERNATE_RECIPE_NAME_PREFIX):
                recipe_name = recipe_name[len(self._ALTERNATE_RECIPE_NAME_PREFIX):]

            recipes[recipe_id] = Recipe(
                recipe_name,
                products,
                ingredients,
                duration,
                is_alternate,
                produced_in
            )

        fuel_byproduct_recipes = self._generate_fuel_byproduct_recipes()

        # Make sure that autogenerated names for the fuel byproduct recipes don't clash with
        # names of real recipes
        assert 0 == len(fuel_byproduct_recipes.keys() & recipes.keys())
        recipes.update(fuel_byproduct_recipes)

        # Post-process recipes
        for recipe_id, recipe in recipes.items():
            # Note: this relies on the fact that Python dir iteration yields items in the order they were inserted.
            # In this case, the insertion order is also the order in which the items appear in the products list.
            for i, (product_id, amount) in enumerate(recipe.products.items()):
                product_obj = self._all_objects[product_id]
                product_recipes = product_obj.get('recipes')
                if product_recipes is None:
                    product_recipes = []
                    product_obj['recipes'] = product_recipes

                # If the recipe is not an alternate, but this product isn't the first in the list, force it to be alternate.
                is_alt = True if 0 != i else recipe.is_alternate

                # Insert the recipe such that non-alternate recipes always come before the
                # alternate recipes
                if is_alt:
                    product_recipes.append(recipe_id)
                else:
                    product_recipes.insert(0, recipe_id)

        return recipes

    # "FGRecipe" doesn't contain byproducts of burning fuel (such as uranium fuel rod -> nuclear waste).
    # This function generates recipes based on other information available in the game data.
    def _generate_fuel_byproduct_recipes(self):
        fuel_byproduct_recipes = {}
        for obj_id, fuel_burner_building in self._all_objects.items():
            if 'mFuel' not in fuel_burner_building:
                continue

            power_production = Fraction(fuel_burner_building['mPowerProduction'])

            for accepted_fuel in fuel_burner_building['mFuel']:
                # Don't care about fuels that don't generate waste
                if not accepted_fuel['mByproduct']:
                    continue

                fuel_obj = self._all_objects[accepted_fuel['mFuelClass']]
                burn_duration = Fraction(fuel_obj['mEnergyValue']) / power_production

                products = {accepted_fuel['mByproduct']: Fraction(accepted_fuel['mByproductAmount'])}
                ingredients = {fuel_obj['id']: Fraction(1)}

                supplemental_resource_id = accepted_fuel['mSupplementalResourceClass']

                # Compute supplemental resource
                if ("True" == fuel_burner_building['mRequiresSupplementalResource']) and \
                   ("" != supplemental_resource_id):
                    ingredients[supplemental_resource_id] = self._normalize_amount(
                        supplemental_resource_id,
                        power_production * Fraction(fuel_burner_building["mSupplementalToPowerRatio"]) * burn_duration
                    )

                dummy_recipe_id = 'Recipe_' + self._OBJECT_NAME_REGEX.match(accepted_fuel['mByproduct'])[2] + '_C'

                fuel_byproduct_recipes[dummy_recipe_id] = Recipe(
                    self._all_objects[accepted_fuel['mByproduct']]['name'],
                    products,
                    ingredients,
                    burn_duration,
                    False,  # TODO: check if there are other ways to generate the byproduct
                    {fuel_burner_building['id']}
                )

        return fuel_byproduct_recipes

    def _process_crafting_objects(self) -> dict[GameObjectId, CraftingObject]:
        crafting_objects: dict[GameObjectId, CraftingObject] = {}
        for crafting_obj_id in self._crafting_ingredients | self._crafting_products:
            obj = self._all_objects[crafting_obj_id]
            if 'recipes' not in obj:
                obj['recipes'] = []

            # If there's a recipe whose name is just the name of the product, consider it the "main" recipe, even if it
            # is currently marked as an alternate recipe
            for i, recipe_id in enumerate(obj['recipes'][1:], 1):
                recipe = self._recipes[recipe_id]
                if recipe.name == obj['name']:
                    recipe_dict = recipe._asdict()
                    recipe_dict['is_alternate'] = False
                    self._recipes[recipe_id] = Recipe(**recipe_dict)
                    del obj['recipes'][i]
                    obj['recipes'].insert(0, recipe_id)
                    break

            # if '/UI/' not in obj['mSmallIcon']:
            #     print(obj['mSmallIcon'])

            assert obj["mForm"] in ("RF_LIQUID", "RF_SOLID", "RF_GAS")
            form = obj["mForm"][len('RF_'):]

            crafting_objects[crafting_obj_id] = CraftingObject(
                obj['id'],
                obj['name'],
                obj['recipes'],
                form
            )

        return crafting_objects

    def _calculate_trivial_ingredients(self) -> set[GameObjectId]:
        # Water is a byproduct of a bunch of things, so it won't be detected by the algorithm below
        trivial_ingredients: set[GameObjectId] = {"Desc_Water_C"}
        for ingredient_id in self._crafting_ingredients:
            ingredient = self._crafting_objects[ingredient_id]
            if (0 == len(ingredient.recipes)) or self._recipes[ingredient.recipes[0]].is_alternate:
                trivial_ingredients.add(ingredient_id)

        # These are wrongfully detected as trivial, since they only have alternate recipes
        trivial_ingredients -= {'Desc_FicsiteIngot_C', 'Desc_DissolvedSilica_C'}

        return trivial_ingredients

    def _parse_crafting_obj_list(self, item_list: str) -> CountedItems:
        items = self._CRAFTING_OBJ_LIST_REGEX.findall(item_list)

        # Make sure that we parsed correctly. Each individual item contains a comma, and theres
        # a comma between every 2 items.
        assert item_list.count(',') == max((len(items) * 2) - 1, 0)

        result = {}
        for item_id, amount in items:
            assert item_id not in result, "Duplicate item appears in list"

            result[item_id] = self._normalize_amount(item_id, Fraction(amount))

        return result

    def _normalize_amount(self, obj_id: str, amount: Fraction) -> Fraction:
        # For some reason, liquid and gas amounts are multiplied by 1000 in the game data
        if self._all_objects[obj_id]['mForm'] in ('RF_LIQUID', 'RF_GAS'):
            amount /= 1000

        return amount

    @classmethod
    def _get_object_display_name(cls, game_object: GameObject) -> str:
        if display_name := game_object.get('mDisplayName', ''):
            return display_name

        # TODO: this yields duplicate names. Need to de-duplicate them by re-adding
        # the prefix on such scenarios

        display_name = game_object['id']
        display_name = cls._OBJECT_NAME_REGEX.match(display_name)
        suffix, display_name = display_name.groups()
        display_name = display_name.replace('_', ' ')
        display_name = cls._CAMEL_CASE_REGEX.sub(r'\1 \2', display_name)

        return display_name


if __name__ == '__main__':
    parser = SatisfactoryParser()
    data = parser.generate_data_file_content()
    with open(path.join(path.dirname(__file__), '..', 'website', 'scripts', 'GameData.auto.mjs'), 'w') as f:
        f.write(data)
